#!/bin/bash

base64 /dev/urandom | head -n 10 > plainText.txt

openssl enc -aes-256-cbc -in plainText.txt -out openSsl-aes-256-cbc -k 973jd9s73j297k

openssl enc -aes-128-cbc -in plainText.txt -out openSsl-aes-128-cbc -k 973jd9s73j297k
